from models.date import DateModel
from models.interest import InterestModel
from models.user import UserModel
from models.user_interest import UserInterestModel
from models.user_stat import UserStatModel
from models.city import CityModel
from models.country import CountryModel
from models.time import TimeModel
from models.kol import KolModel
from models.alembic_version import AlembicVersionModel
from models.age import AgeModel
from models.fan_demo_age import FanDemoAgeModel
from models.fan_demo_gender import FanDemoGenderModel
from models.fan_demo_city import FanDemoCityModel
from models.fan_demo_country import FanDemoCountryModel
from models.fan_demo_interest import FanDemoInterestModel
